services:
  app:
    build: .
    container_name: StalHub_backend
    command: bun run --watch src/index.ts
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: StalHub_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data: