name: Deploy

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -e

            cd /var/www/stalhub_backend
            git fetch origin
            git reset --hard origin/main
            git clean -fd
            docker compose up -d --build